import { ReactNode } from 'react';

export const metadata = {
  title: 'Default Title',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  locale = 'en',
}: {
  children: ReactNode;
  locale: string;
}) {
  return (
    <html lang={locale}>
      <body>{children}</body>
    </html>
  );
}
