import { ReactNode } from 'react';

import GlobalProvider from '@/store/GlobalProvider';

export const metadata = {
  title: 'Default Title',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  params,
}: {
  children: ReactNode;
  params: { locale: string };
}) {
  return (
    <html lang={params.locale || 'en'}>
      <body>
        <header></header>
        <GlobalProvider>{children}</GlobalProvider>
      </body>
    </html>
  );
}
